/**
 * Error codes for transaction-related errors.
 */
export const TRANSACTION_ERROR_CODES = {
  NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  INVALID_AMOUNT: 'TRANSACTION_INVALID_AMOUNT',
  INVALID_TYPE: 'TRANSACTION_INVALID_TYPE',
  INVALID_MERCHANT: 'TRANSACTION_INVALID_MERCHANT',
  INVALID_SOURCE: 'TRANSACTION_INVALID_SOURCE',
  SYNC_FAILED: 'TRANSACTION_SYNC_FAILED',
  DUPLICATE_HASH: 'TRANSACTION_DUPLICATE_HASH',
} as const;

export type TransactionErrorCode = typeof TRANSACTION_ERROR_CODES[keyof typeof TRANSACTION_ERROR_CODES];
